# Generated by Django 4.2.5 on 2023-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_test_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenNovels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('outline', models.TextField()),
                ('url', models.TextField()),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NovelsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('outline', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('words', models.IntegerField()),
                ('year', models.IntegerField()),
                ('collectedCount', models.IntegerField()),
                ('url', models.TextField()),
                ('website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestNovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('outline', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
