# Generated by Django 4.2.5 on 2023-09-21 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0003_chosennovels_novelsinfo_testnovel_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookshelf', models.CharField(max_length=200)),
                ('folder', models.CharField(max_length=200)),
                ('novel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.chosennovels')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
