# Generated by Django 4.2.5 on 2023-10-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_bookshelf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelf',
            old_name='novel_id',
            new_name='novel',
        ),
        migrations.RenameField(
            model_name='bookshelf',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='novelsinfo',
            old_name='collectedCount',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='novelsinfo',
            old_name='words',
            new_name='size',
        ),
    ]
