# Generated by Django 4.2.5 on 2023-10-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_rename_novel_id_bookshelf_novel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='url_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
